language: php
php:
- '7.1'
env:
  global:
  - ZIP_FILENAME=bmlt-tabbed-ui-build${TRAVIS_BUILD_NUMBER}-${TRAVIS_COMMIT}.zip
jobs:
  include:
  - stage: lint
    install:
    - composer install
  - stage: zip file
    env:
    - BUILD_DIR=build
    - DIST_DIR_GITHUB=dist/github
    - GITHUB_RELEASE_FILENAME=bmlt-tabbed-ui.zip
    - PLUGIN="bmlt-tabbed-ui"
    - MAINFILE="bmlt-tabbed-ui.php"
    script:
    - find ./ -type d | xargs chmod 755
    - find ./ -name '*.php' | xargs chmod 644
    - zip -r $ZIP_FILENAME ./ -x "*.git*" -x "*.editorconfig*" -x "*.travis.yml*"
      -x "*assets*" -x "*vendor*" -x "composer.*" && mkdir $BUILD_DIR && mv $ZIP_FILENAME
      $BUILD_DIR/
    before_deploy:
    - mkdir -p $DIST_DIR_GITHUB && cp $BUILD_DIR/$ZIP_FILENAME $DIST_DIR_GITHUB/$GITHUB_RELEASE_FILENAME
    deploy:
    - provider: releases
      otrokfile: "$DIST_DIR_GITHUB/$GITHUB_RELEASE_FILENAME"
      skip_cleanup: true
      name: "$TRAVIS_TAG"
      on:
        tags: true
notifications:
  slack:
    secure: X99q0tRkx6b+igdA54zqOWPVeujLVohbGTdbYGXAtypFhzrZ/v12nNW6QMARvx7i9+LifRgcCzIdnw0DtVi4G5FCxbA9sdUKBpAWAxpzklhhNIDyIS8PMhARxylZb3aB9ie5UWeblwVt9PeOfwd4F8Fz25ZMME8UkDkRJS0kymXzmGj7Jm5k+C7TqMmxK9LkB42Iby9btC0MjLFtIHsaEHrflCvP1U8Gc0gfeazg2aRJPLLrACj5ObGpFLQ0xxBCfzTxS64AjWozO7zTYZu+6YKtUdsEMKHf5wh6MG1TyBb0OBC7CJNPf4ULbmmP+/Pjn2Gylva77/ElGSZJcOXKDaMGhFtmxtN9/ZhoSLZ+ntMccWkTdqePb14xs6uQifj2Qi4r9SiIf/aeED2DURdzDynJaH17QE+KxQ2hdH/L3xkPByqG0Px/O61Gpcwc8ng29tsns4tWMh+FGv3rShXWUUnyisfQhHlw+2aAHlqubDkt/4m3CluazwIH2lliz0HNUXfrs2rOaNT0vdKmYe1fKJDGsMvQG49xwIZKSKVUmRqNVzHCgz8v/ZfvVl15eq2Uzv+8vmo524YRLAzFyiReBMQRfrNts1fE/hwOEXLEwDrnMOYnzb9nMM9w9EHTbcpu638I4hRlhwzYLEtdZh9MkBBfz27jhdhrs9g2RynXhg4=
  email: false
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key 
  -in github_deploy_key.enc -out github_deploy_key -d
